# Generated by Django 4.1 on 2022-11-19 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_likeforcomment_target_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='post_image',
        ),
    ]
