# Generated by Django 4.1 on 2022-11-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default='', max_length=30, verbose_name='ユーザーネーム'),
        ),
    ]
