# Generated by Django 4.1 on 2023-01-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_username_customuser_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='picture',
            field=models.ImageField(default='profile/default.png', upload_to='profile/', verbose_name='プロフィール画像'),
        ),
    ]
